### ISSUE TITLE
NoGlutinConfigs on NixOS

### ISSUE THREAD

**Issue by nuxeh** [hacknus/serial-monitor-rust#100]
Hi, I would love to be able to run `serial-monitor-rust`, I have been searching for something like this for a very long time.

However, I'm having great difficulty getting it running on NixOS, with this runtime error at start:

```
starting connection thread..
starting main thread..
error: NoGlutinConfigs(ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }, Error { raw_code: None, raw_os_message: None, kind: NotFound })
```

It seems to be some deep seated issues with the `glow` backend on NixOS, and some have solved it by using `wgpu` as the backend instead, the trouble is I can't work out how to do that.

I know Rust, but I have no idea when it comes to graphics, and wondered, whether it's something that could be done in `serial-monitor-rust`, to use `wgpu` optionally for a backend, and if that would be easy enough to do?

**Comment by hacknus** [comment]
Hi!

Thanks a lot for giving this a try!
According to [egui](https://github.com/emilk/egui), it should be as simple as updating the following line in the `cargo.toml` file, just add the wgpu feature:
```toml
eframe = { version = "0.27", features = ["persistence", "wgpu"] }
```

**Comment by hacknus** [comment]
closing this, feel free to re-open if the comment above does not solve the issue..
