### ISSUE TITLE
Choose the color for the plotting.

### ISSUE THREAD

**Issue by clroute66** [hacknus/serial-monitor-rust#101]
Hello, it would be nice to choose the color of the plot,  I have 9, CSV being input to the software it would be nice to select the color.

it also would be nice to be have a vertical line to follow the plots.
thanks it is a nice program and very fast and light.
-CL

**Comment by hacknus** [comment]
hello, thanks for the input!
choosing plot colors is a nice idea!
However I do not understand what you mean by vertical line that follows the plot?

also: how do you take the CSV as an input for the software?

**Comment by hacknus** [comment]
I see, thanks!
The serial monitor should have a vertical and horizontal line in the plot at the location of the cursor - is that not the case for you?

![Uploading Bildschirmfoto 2024-09-26 um 17.25.12.png…]()

**Comment by clroute66** [comment]
yes I have used that function, some times with the plot being big make it hard to pin point the number you are looking at, could it follow the trace of the plot (data) as a option?

**Comment by hacknus** [comment]
aaah, now I get it! you want that cursor/line to always follow the latest datapoint? I'm not sure if that wouldn't make the plot too cluttered if there are many datapoints on it..

**Comment by clroute66** [comment]
when you zoom in one the plot it should focused just the one plot?

**Comment by hacknus** [comment]
yes, but in your image on the bottom, the blue, yellow and white line are pretty close together, so if all cursors are always shown, they could easily cause overlay and cluttering...

**Comment by hacknus** [comment]
Color picker has been implemented in the latest release
