### ISSUE TITLE
only one dataset display in the plot even there are 3

### ISSUE THREAD

**Issue by allrightsreserved** [hacknus/serial-monitor-rust#109]
Awesome project! 
but there has an issue: three dataset was detected but only first one is showed from plot in V0.3.1
![v0 3](https://github.com/user-attachments/assets/0f71ce14-6af5-44ea-a087-fcc49ed46cef)

the older version(v0.2.1) can show 3 datasets as expected, after the reset label was clicked :
![Version 0 2 1](https://github.com/user-attachments/assets/4aa0007c-63a2-4591-aa86-60d26d05df5d)

**Comment by hacknus** [comment]
Hi, thanks for testing!
Does it help if you click "Reset Labels" ?

**Comment by allrightsreserved** [comment]
Hi,nothing happening after click "Reset Labels", still one curve there.

**Comment by hacknus** [comment]
hmm, really weird. also that your colors do not correspond to the labeled ones. Can you change the labels and colors for the three curves? does that change something?

**Comment by allrightsreserved** [comment]
I'm using win11 x64, it's the same after change the color and labels ,and then "reset labels",
![image](https://github.com/user-attachments/assets/47c09a76-a3a4-49e0-8d25-49707c85e7a0)

**Comment by hacknus** [comment]
Ok, thanks a lot, I will look into that!

**Comment by hacknus** [comment]
Fixed.
Release: [v0.3.2](https://github.com/hacknus/serial-monitor-rust/releases/tag/v0.3.2)

**Comment by allrightsreserved** [comment]
![image](https://github.com/user-attachments/assets/c6af576a-5017-4247-b736-118a7c0de315)
perfect, thank you!
