### ISSUE TITLE
Offer to contribute to improving code quality

### ISSUE THREAD

**Issue by lonesometraveler** [hacknus/serial-monitor-rust#2]
Hello there,

I came across your project and noticed that the codebase could benefit from some improvements to its quality. Specifically, I think running Clippy would help identify and fix many of the issues in the code.

I am interested in contributing to this project, and I believe improving the code quality would be a good first step. I would like to ask if you would be open to me submitting pull requests or working with you to make the changes.

**Comment by hacknus** [comment]
that sounds great! Sure, I'd appreciate any inputs!

**Comment by lonesometraveler** [comment]
Great. Thanks. I will send many small PRs instead of one huge PR.
