### ISSUE TITLE
Question about `serial_write` and acknowledgment

### ISSUE THREAD

**Issue by lonesometraveler** [hacknus/serial-monitor-rust#27]
```rust
fn serial_write(port: &mut BufReader<Box<dyn SerialPort>>, cmd: &[u8]) -> bool {
    let write_port = port.get_mut();
    match write_port.write(cmd) {
        Ok(_) => {
            let mut response = "".to_string();
            serial_read(port, &mut response);
            println!("sent a command!");
            if response.contains("OK") {
                true
            } else {
                println!("cmd not acknowledged!!!");
                false
            }
        }
        Err(_) => false,
    }
}
```

The code expects a connected device to send back a string that contains `"OK"` each time it receives a command. I am not sure if this is a reliable way to handle a response, as the device on the other end may not have processed the command yet or may take some time to send a response.

Also, even if a device can respond quickly enough, I am not sure if the app can always read a `"OK"`. Doesn't the app read whatever data in the RX buffer? Let's say a device sends `"0.1"` 100 times a second. The device sends back `"OK"` when it receives a command. When the app calls `serial_read`, does it always read `"OK"`? Or sometimes it reads `"0.1"`?

**Comment by hacknus** [comment]
Yes, you are completely correct. This part of the code is very specific to my current embedded project and should not at all be used as a standard. We can **leave out the `serial_read` call**, it is not used further in the App.

For a different application - where we would want to wait for an acknowledgement - we would have to read out the buffer and wait for the acknowledge signal as you mention (and probably with a timeout, let's say 2 seconds):

```
    match write_port.write(cmd) {
        Ok(_) => {
            let mut response = "".to_string();
            let t_send = Instant::now();
            let mut ack = false;
            println!("sent a command!");
            while !ack && Instant::now().duration_since(t_send).as_secs() < 2 {
                serial_read(port, &mut response);
                if response.contains("OK") {
                    println!("cmd acknowledged: {response:?}");
                    ack = true;
                } else {
                    println!("cmd not acknowledged: {response:?}");
                    response = "".to_string();
                }
            }
            ack
        }
        Err(_) => false,
    }
```

**Comment by lonesometraveler** [comment]
Ok. We forget about ACK for now. I think `serial_write` should return `Result` instead of `bool`. I propose something like this.

```rust
fn serial_write(
    port: &mut BufReader<Box<dyn SerialPort>>,
    cmd: &[u8],
) -> Result<usize, std::io::Error> {
    let write_port = port.get_mut();
    write_port.write(cmd)
}
```

**Comment by hacknus** [comment]
Agreed! 👍
