### ISSUE TITLE
Wrong displaying time

### ISSUE THREAD

**Issue by wojtess** [hacknus/serial-monitor-rust#59]
When build with -r flag, the plot is displayed wrong.
![image](https://user-images.githubusercontent.com/49391462/224426211-5d78ce88-8524-4fb9-b930-dc4dba84943e.png)
This is how it looks like in debug build:
![image](https://user-images.githubusercontent.com/49391462/224426325-a7fd6896-a442-4748-97b4-885942cb3e8a.png)

**Comment by hacknus** [comment]
You are correct, this is a bug. The values in the plot are actually in milli seconds, not seconds. So we can either change the label on the x-axis to ms or we can change the values to seconds, as in the console.

For me this makes no difference in release or debug mode. Can you double-click the plot to re-center it? Then the two plots should look the same in debug and release, right?

**Comment by wojtess** [comment]
Yes I can center it when I double click it, I didnt know about that. Thans for help.

Also I think the ploter shoud have two modes, normal and osciloscope where You can zoom to the for ex last 10sec and follow signal.

**Comment by hacknus** [comment]
@wojtess you can use the "plotting range" input to the right, when set to -1 the full dataset is shown, when put to 10, only the last 10 entries are shown and followed.

You are right, we could think about also implementing this range in units of time, not just number of datapoints.
