### ISSUE TITLE
Better dataset identification/selection

### ISSUE THREAD

**Issue by RoccoEE** [hacknus/serial-monitor-rust#81]
Hi, 
I have a device where the output data is as so 
`[RECV] t + 210.359s: #,00:00:00 00/00/0000,          ,          ,    .0862,         ,N.m, VCX000002, 1`
A feature for a custom separator would be pretty awesome

**Comment by hacknus** [comment]
@RoccoEE `'s '` should already be implemented as separator. Can you post a screenshot of what the serial monitor is displaying?

**Comment by RoccoEE** [comment]
![output](https://github.com/hacknus/serial-monitor-rust/assets/47798035/5a3a9e51-8906-4190-ad56-47d5316c8328)

**Comment by hacknus** [comment]
@RoccoEE sorry, I meant a full screenshot of the plot. The separator only matters for the plot. Below as text you always find the raw data that gets printed over serial.

**Comment by RoccoEE** [comment]
Sorry yeah i updated the post after i re-read it

**Comment by hacknus** [comment]
@RoccoEE The plot should be showing once it detects 10 or more printed lines with the same structure.

**Comment by RoccoEE** [comment]
![image](https://github.com/hacknus/serial-monitor-rust/assets/47798035/ee0841e4-de8e-4c68-9eea-ff21dc5d0f4d)
Okay yeah just getting a flat line now. Says there is 4 detected datasets but theres only one plotline and box

**Comment by hacknus** [comment]
@RoccoEE Seems like bug #80, try to hit the "Reset Labels" button and double click on the plot (to re-center).
What does the legend show in the plot?
it could be that the serial monitor is only able to parse the last line with the 1. Never tried to parse float without the leading 0 (e.g. .0136).

**Comment by hacknus** [comment]
What kind of device settings did you adjust?
Agreed, we should implement the possibility to reset the saved config file.

**Comment by RoccoEE** [comment]
```
[RECV] t + 126.772s: #,00:00:00 00/00/0000,          ,          ,    .1937,         ,N.m, VCX000002, 1
							^cont     ^peak     ^1st
```
Depending on the device setting the data will be spat out into each of those fields

**Comment by hacknus** [comment]
@RoccoEE Do you mean a setting on the device itself (hardware) or a setting on the Serial Monitor (e.g. baud rate etc) ?

**Comment by RoccoEE** [comment]
Apologies yeah a setting on the device.

**Comment by hacknus** [comment]
Since this seems to be an issue on the device-side I'm closing this issue.
