### ISSUE TITLE
Support for multiple plots

### ISSUE THREAD

**Issue by Pryning** [hacknus/serial-monitor-rust#82]
When data columns are in very different ranges it is impossible to view.

It would be very useful if the user could create multiple plots and select which data columns goes where.
Multiple Y-axis' would also be a great addition.

**Comment by hacknus** [comment]
Thanks @Pryning! That's a really great idea. While I think that multiple plots could become too cluttering, I'd like the option for a second y-axis. However it requires quite some modifications on the plot widget ([egui](https://github.com/emilk/egui)). The plot implementation of this project is found in [gui.rs, in function draw_central_panel()](https://github.com/hacknus/serial-monitor-rust/blob/main/src/gui.rs#L302).
I do currently not have time to implement this, but pull-requests are welcome!

**Comment by hacknus** [comment]
@Pryning As a workaround for now (what I do for cases where different values with different orders of magnitude):
You can select which values you want to display by clicking on the labels in the legend. It's a bit tedious and not elegant, but this way you can isolate certain columns.

**Comment by Pryning** [comment]
I get that and it was also more of an item to add to your list of great features to one day add.
Sadly I am not a Rust developer (yet) so I can only contribute ideas :)

And thanks for the workaround, I will try to use it like that 👍
