### ISSUE TITLE
crash when selecting device

### ISSUE THREAD

**Issue by hacknus** [hacknus/serial-monitor-rust#84]
The latest code crashes because we get an out of bounds error in `./src/gui.rs:690:66`:
```rust
self.serial_devices.number_of_plots[self.device_idx]
```
we need to make sure that number_of_plots is extended/updated when a new device is connected.

  
Workaround:  
use the latest release

**Comment by dogan-eren** [comment]
See line
https://github.com/hacknus/serial-monitor-rust/blame/8dff2bd89b71c162164ef79062da71f8683d446d/src/gui.rs#L552

Line:
self.device_idx = idx;

Why not
self.device_idx = idx - 1;

**Comment by hacknus** [comment]
@dogan-eren Thanks! But I think the issue is that `self.serial_devices.number_of_plots` does not get extended when a new device is connected, so when we select a new device, we get an out of bound indexing.

A similar issue exists with the labels. When a new device is connected, one has to hit "Clear labels" to have everything shown.

**Comment by hacknus** [comment]
Should be fixed now, one might have to "Clear Device History" to migrate to the new version.
