### ISSUE TITLE
Migrate to `serial2` crate?

### ISSUE THREAD

**Issue by jarkkojs** [hacknus/serial-monitor-rust#94]
I found out by talking to the maintainer that the added benefit of using `serial2` crate is its better support for Windows: https://docs.rs/serial2/latest/serial2/. So taking this into use would make serial monitor more cross-platform enabled than it is today.

**Comment by hacknus** [comment]
interesting, what are the benefits specifically? the `serial` crate does also work on windows currently.

**Comment by jarkkojs** [comment]
> interesting, what are the benefits specifically? the `serialport-rs` crate does also work on windows currently.

https://github.com/de-vri-es/serial2-rs/issues/6#issuecomment-1837197691

**Comment by hacknus** [comment]
Thanks, I upgraded it on [this branch](https://github.com/hacknus/serial-monitor-rust/tree/implement_serial2), but I haven't tested it yet.

**Comment by hacknus** [comment]
@jarkkojs apparently there is an issue with high data rates and the serial2 crate, see #98
