### ISSUE TITLE
[New Feature]: associate timeseries to different plots. 

### ISSUE THREAD

**Issue by ubaldot** [hacknus/serial-monitor-rust#99]
It would be nice to associate timeseries to graphs and have the opportunity to display multiple graphs at the same time.

For example, by assuming to receive data streams from three sensors, one should be able to plot sensorValues1 and sensorValues2 on the first graph and sensorValues3 on the second graph.

**Comment by hacknus** [comment]
Hi, thanks for checking in!

If I understand you correctly this is possible in the latest version. you can increase the number of plots and then just select sensorValue1, sensorValue2 in the legend on plot 1, and sensorValue3 on plot 2 and so on... 

I haven't gotten around to create a new release since this has been added, so you have to pull the master branch and compile it yourself for the new features.

**Comment by ubaldot** [comment]
Awesome! But tbh I don’t feel like to compile, I will wait the release for apple silicon. :)

**Comment by hacknus** [comment]
fair enough! now I have a motivation to push for a release! I'll look into it as soon as I can!

**Comment by ubaldot** [comment]
Infinitely thanks! The possibility of associating timeseries to graphs would be a killer feature that I haven't seen in any other project. Please, close this issue once done so that I get notified. :) Thanks again!

**Comment by hacknus** [comment]
@ubaldot enjoy:
https://github.com/hacknus/serial-monitor-rust/releases/tag/v0.2.0

I'm always happy to get feedback! :)

**Comment by ubaldot** [comment]
Hey thank you! I will give it a go later on today or tomorrow. :) I will only use the silicon version because I have an M1 MacBook. I will let you know, thanks again!

**Comment by hacknus** [comment]
I think the apple silicon build is queued for some reason.. use the normal build for macos, it should also run on apple silicon, just not as optimized.

**Comment by ubaldot** [comment]
Hello! I finally give it a go! Awesome job! I was actually impressed how beauty and easy is the interface. 
Some feedbacks:

1. Some docs would be great to have (I may contribute in that case)
2. Possibility to collapse the side menu and the bottom display information
3. Possibility to actually add/remove a dataset in a plot rather than enabling/disabling it
4. Possibility to choose colour, thickness and linestyle for each dataset (e.g. "continuous, red, thin", "dashed, blue, thick", etc) 
5. Plotting range units should be "n. points" rather than "#". 
6. I don't use it but perhaps some users may want to use a binary format for data streams.
7. Many macos users will skip the download if they don't explicitly read ARM in the releases (mind that users are LAZY!). 

![Screenshot 2024-03-10 at 19 17 32](https://github.com/hacknus/serial-monitor-rust/assets/10845685/e4156ae8-bea3-4133-9c88-ea9c7f4741d0)


I will definitely used it for my YouTube channel contents once I will start to move from theory to practice. :)

**Comment by hacknus** [comment]
> 1. Some docs would be great to have (I may contribute in that case). 

Agreed! There is also a feature request (#76 ) open about a how-to start guide, but I haven't gotten around to that... 
> 2. Y-axes lock range. 

👍🏻
> 3. Possibility to collapse the side menu and the bottom display information. 

👍🏻
> 4. Possibility to actually add/remove a dataset in a plot in addition to enabling/disabling it. 

Not quite sure what you mean, but any further interaction with the legend would need to be implemented in [egui](https://github.com/emilk/egui)
> 5. Possibility to choose colour, thickness and linestyle for each dataset (e.g. "continuous, red, thin", "dashed, blue, thick", etc). 

👍🏻
> 6. Plotting range units should be "n. points" rather than "#".  

👍🏻
> 7. I don't use it but perhaps some users may want to use a binary format for data streams.  

👍🏻
> 8. Many macos users will skip the download if they don't explicitly read ARM in the releases (mind that users are LAZY!).  

haha fair enough, it will be renamed for the next release


Thank you very much for the feedback, really appreciate it!

**Comment by ubaldot** [comment]
Here I am. Sorry, I finally found some time to follow up. 

> Not quite sure what you mean, but any further interaction with the legend would need to be implemented

I'll make an example: say that I have 10 signals and I want to plot 3 in the first graph and 7 in the second graph. As it is not, I would have 10 signals and 10 legend in both the graphs. Then, I can disable 7 signals in the first graph and 3 signals in the second graph to hide them, but the legend would still have 10 items in both the graphs. Hope it clarifies a bit :)

**Comment by hacknus** [comment]
Ah okay, I see. yes, we could put a color picker and a plot-selection-dropdown menu next to the text-field where we type in the label/name of the dataset? something like this?

**Comment by ubaldot** [comment]
Yes, for the plot selection. 
For the color I would conveniently use the triple (color, linestyle, thickness) instead, where for color one could take the color engine of the OS, linestyle is a dropdown menu where user can choose ‘continuous’, ‘dashed’, etc and thickness is a positive integer. 

I can make a sketch tomorrow (now I am not at home).
